# Generated by Django 5.0.14 on 2026-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-date_joined"]},
        ),
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email / Password"),
                    ("GOOGLE", "Google"),
                    ("ZOHO", "Zoho"),
                    ("INTERNAL", "Internal Service"),
                ],
                default="EMAIL",
                help_text="Authentication provider used on first login",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="catalyst_user_id",
            field=models.CharField(
                blank=True,
                help_text="Zoho Catalyst User ID (from Catalyst Auth)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_via_catalyst",
            field=models.BooleanField(
                default=False,
                help_text="True if this account was auto-created on first Catalyst login",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Full display name from Catalyst / OAuth provider",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_profile_complete",
            field=models.BooleanField(
                default=False,
                help_text="True after user completes onboarding (e.g. sets badge number)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent successful authentication timestamp",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image_url",
            field=models.URLField(
                blank=True,
                help_text="Avatar URL from Google/Zoho profile",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("INVESTIGATOR", "Investigator"),
                    ("ANALYST", "Crime Analyst"),
                    ("SUPERVISOR", "Supervisor"),
                    ("POLICYMAKER", "Policymaker"),
                    ("USER", "User"),
                ],
                default="INVESTIGATOR",
                max_length=20,
            ),
        ),
    ]
