# Generated by Django 5.0.14 on 2026-07-22 03:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_uri', models.CharField(help_text='URI of the data source', max_length=2048, unique=True)),
                ('source_type', models.CharField(help_text='e.g. pdf, postgres, mysql', max_length=100)),
                ('metadata_payload', models.JSONField(blank=True, default=dict, help_text='Metadata extracted by the adapter')),
                ('profile_payload', models.JSONField(blank=True, default=dict, help_text='Data profiling information')),
            ],
            options={
                'verbose_name_plural': 'Adapter Metadata',
                'db_table': 'adapter_metadata',
            },
        ),
    ]
