from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class ToolType(str, Enum):
    SQL = "sql"
    PYTHON = "python"
    GRAPH = "graph"
    RAG = "rag"
    ANALYTICS = "analytics"
    VISUALIZATION = "visualization"
    FORECAST = "forecast"  # OPTIONAL — only invoked for explicit prediction queries


class DependencyType(str, Enum):
    INDEPENDENT = "independent"  # Can run in parallel with any other independent tool
    AFTER_SQL = "after_sql"      # Needs SQL tool results before running
    AFTER_GRAPH = "after_graph"  # Needs Graph tool results before running
    AFTER_ALL = "after_all"      # Must run after ALL independent tools complete


class Subtask(BaseModel):
    """A single decomposed sub-question from a multi-hop query."""

    subtask_id: str = Field(default_factory=lambda: str(uuid4())[:8])
    description: str
    question_fragment: str
    required: bool = True


class ToolCall(BaseModel):
    """A single tool invocation directive within an ExecutionPlan."""

    tool: ToolType
    priority: int = 1                                    # Lower = higher priority group
    dependency: DependencyType = DependencyType.INDEPENDENT
    rationale: str
    parameters: dict[str, Any] = Field(default_factory=dict)
    subtask_id: str | None = None                        # Links to a Subtask


class ExecutionPlan(BaseModel):
    """
    Generated by the Planning Agent after querying the ToolCapabilityRegistry.
    Consumed by QueryDecompositionAgent and ToolRouterAgent.
    """

    plan_id: str = Field(default_factory=lambda: str(uuid4()))
    original_question: str
    intent: str = "case_lookup"
    complexity: str = "simple"       # simple | moderate | complex | multi_hop
    subtasks: list[Subtask] = Field(default_factory=list)
    tool_calls: list[ToolCall] = Field(default_factory=list)
    reasoning_notes: str = ""
    requires_clarification: bool = False
    clarification_question: str | None = None
    available_tools: list[str] = Field(default_factory=list)  # Populated from registry
