import os
import django
from django.db import connection

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

def fix():
    with connection.cursor() as cursor:
        try:
            print("Fixing casemaster PK...")
            cursor.execute("ALTER TABLE casemaster ALTER COLUMN casemasterid ADD GENERATED BY DEFAULT AS IDENTITY;")
        except Exception as e:
            print(f"casemaster error: {e}")

        try:
            print("Fixing victim PK...")
            cursor.execute("ALTER TABLE victim ALTER COLUMN victimmasterid ADD GENERATED BY DEFAULT AS IDENTITY;")
        except Exception as e:
            print(f"victim error: {e}")

        try:
            print("Fixing accused PK...")
            cursor.execute("ALTER TABLE accused ALTER COLUMN accusedmasterid ADD GENERATED BY DEFAULT AS IDENTITY;")
        except Exception as e:
            print(f"accused error: {e}")

        try:
            print("Fixing complainantdetails PK...")
            cursor.execute("ALTER TABLE complainantdetails ALTER COLUMN complainantid ADD GENERATED BY DEFAULT AS IDENTITY;")
        except Exception as e:
            print(f"complainantdetails error: {e}")
            
        print("All Primary Keys are now Auto-Incrementing!")

if __name__ == "__main__":
    fix()
