# Generated by Django 5.0.14 on 2026-07-20 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accused",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="accusedmasterid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="accusedname", max_length=255, null=True
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, db_column="ageyear", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_column="gender",
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, db_column="contact_number", max_length=50, null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, db_column="address", null=True),
                ),
                (
                    "criminal_history",
                    models.TextField(
                        blank=True, db_column="criminal_history", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUSPECT", "Suspect"), ("ACCUSED", "Accused")],
                        db_column="status",
                        default="SUSPECT",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "accused",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ClueEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("PHONE_NUMBER", "Phone Number")], max_length=30
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "cases_clueentity",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Complainant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="complainantid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_column="complainantname",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, db_column="ageyear", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_column="gender",
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, db_column="contact_number", max_length=50, null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, db_column="address", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "complainantdetails",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FIR",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="casemasterid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fir_number",
                    models.CharField(
                        blank=True, db_column="crimeno", max_length=100, null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="brieffacts", null=True),
                ),
                (
                    "incident_date_time",
                    models.DateTimeField(
                        blank=True, db_column="incidentfromdate", null=True
                    ),
                ),
                (
                    "reported_date_time",
                    models.DateTimeField(
                        blank=True, db_column="crimeregistereddate", null=True
                    ),
                ),
                (
                    "crime_type",
                    models.CharField(
                        choices=[
                            ("THEFT", "Theft"),
                            ("BURGLARY", "Burglary"),
                            ("ROBBERY", "Robbery"),
                        ],
                        db_column="crime_type",
                        default="THEFT",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_INVESTIGATION", "Under Investigation"),
                        ],
                        db_column="status",
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, db_column="location", max_length=255, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_column="latitude",
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_column="longitude",
                        decimal_places=6,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "casemaster",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("timestamp", models.DateTimeField()),
                ("is_suspicious", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Victim",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="victimmasterid", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="victimname", max_length=255, null=True
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, db_column="ageyear", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_column="gender",
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, db_column="contact_number", max_length=50, null=True
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, db_column="address", null=True),
                ),
                (
                    "statement",
                    models.TextField(blank=True, db_column="statement", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
            ],
            options={
                "db_table": "victim",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accused",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_accounts",
                        to="cases.accused",
                    ),
                ),
            ],
        ),
    ]
