# Generated by Django 5.0.14 on 2026-07-20 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fir",
            name="officer_in_charge",
            field=models.ForeignKey(
                blank=True,
                db_column="officer_in_charge_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complainant",
            name="fir",
            field=models.ForeignKey(
                blank=True,
                db_column="casemasterid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complainants",
                to="cases.fir",
            ),
        ),
        migrations.AddField(
            model_name="clueentity",
            name="fir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="cases.fir",
            ),
        ),
        migrations.AddField(
            model_name="accused",
            name="fir",
            field=models.ForeignKey(
                blank=True,
                db_column="casemasterid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accused",
                to="cases.fir",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transactions",
                to="cases.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="target_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_transactions",
                to="cases.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="victim",
            name="fir",
            field=models.ForeignKey(
                blank=True,
                db_column="casemasterid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victims",
                to="cases.fir",
            ),
        ),
    ]
