import logging
from typing import Dict, Any, List

from .exceptions import InvalidProfileError

logger = logging.getLogger(__name__)

class RiskExplainer:
    """
    Interprets mathematical and heuristic ML models (like the Profiling module)
    and translates them into human-readable insights for law enforcement officers.
    """
    
    def explain_risk_score(self, profile: Dict[str, Any]) -> List[str]:
        """
        Parses a generated profile and returns a list of reasons that justify
        the computed risk score.
        
        Args:
            profile: The dictionary profile generated by `ProfileGenerator.generate_suspect_profile`.
            
        Returns:
            A list of string explanations.
        """
        if "total_cases" not in profile or "known_associates_count" not in profile or "risk_score" not in profile:
            raise InvalidProfileError("Profile is missing required fields (total_cases, known_associates_count, risk_score).")
            
        explanations = []
        cases = profile["total_cases"]
        associates = profile["known_associates_count"]
        score = profile["risk_score"]
        
        explanations.append(f"Base risk score evaluated to {score} out of 100.")
        
        if cases == 0:
            explanations.append("The subject has no prior recorded offenses in the knowledge graph.")
        elif cases == 1:
            explanations.append("Score elevated by +20 due to the presence of a baseline criminal offense.")
        else:
            penalty = 20 + ((cases - 1) * 15)
            explanations.append(f"Score heavily elevated by +{penalty} due to a pattern of repeat offenses ({cases} total cases).")
            
        if associates > 0:
            assoc_penalty = associates * 5
            explanations.append(f"Score elevated by +{assoc_penalty} due to connections with {associates} known criminal associate(s).")
            
        if score == 100:
            explanations.append("WARNING: The risk score has reached the maximum threshold (100) indicating an extreme threat level or highly organized syndicate member.")
            
        return explanations
